language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - rustup target add thumbv7em-none-eabihf

script:
  - cargo build --verbose

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
